kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Values.namespace }}
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Values.namespace }}
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}
          env:
            - name: CONFIG_PATH
              value: {{ .Values.configLocation }}
          volumeMounts:
            - mountPath: {{ .Values.configLocation }}
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-config
