kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.namespace }}
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
data:
  TOKEN: ''